### ISSUE TITLE
Stopped working since AppDaemon 0.15.x

### ISSUE THREAD

**Issue by Robi1976** [nechry/elco-remocon-net-appdaemon#8]
Hi Nechry,

Whole Appdaemon configuration has been moved from /config to /addon_configs folder since version 0.15.x. My Remocon sensors stopped working. I tried the following:

I was able to change appdaemon.yaml in /addon_configs folder as follows (changed secrets path and added app_dir):

```
secrets: /homeassistant/secrets.yaml
appdaemon:
  time_zone: CET
  latitude: 51.725
  longitude: 14.3434
  elevation: 0
  app_dir: /homeassistant/appdaemon/apps
  plugins:
    HASS:
      type: hass
      ha_url: http://homeassistant.local:8123
      token: !secret appdaemon_token
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:

```
I linked your HACS-Backend with the app_dir function. Appdaemon is up and running and adds your module (see below) but the Sensors are not working.

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

 Add-on: AppDaemon
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant

 Add-on version: 0.15.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.1  (aarch64 / odroid-n2)
 Home Assistant Core: 2023.11.3
 Home Assistant Supervisor: 2023.11.3

 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.

s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
[10:33:42] INFO: Starting AppDaemon...
s6-rc: info: service legacy-services successfully started
2023-11-24 10:33:46.236904 INFO AppDaemon: AppDaemon Version 4.4.2 starting
2023-11-24 10:33:46.237166 INFO AppDaemon: Python version is 3.11.6
2023-11-24 10:33:46.237331 INFO AppDaemon: Configuration read from: /config/appdaemon.yaml
2023-11-24 10:33:46.237489 INFO AppDaemon: Added log: AppDaemon
2023-11-24 10:33:46.237675 INFO AppDaemon: Added log: Error
2023-11-24 10:33:46.237832 INFO AppDaemon: Added log: Access
2023-11-24 10:33:46.237988 INFO AppDaemon: Added log: Diag
2023-11-24 10:33:46.461881 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2023-11-24 10:33:46.708646 INFO HASS: HASS Plugin Initializing
2023-11-24 10:33:46.708903 INFO HASS: HASS Plugin initialization complete
2023-11-24 10:33:46.709424 INFO AppDaemon: Initializing HTTP
2023-11-24 10:33:46.709872 INFO AppDaemon: Using 'ws' for event stream
2023-11-24 10:33:46.713684 INFO AppDaemon: Starting API
2023-11-24 10:33:46.716230 INFO AppDaemon: Starting Admin Interface
2023-11-24 10:33:46.716755 INFO AppDaemon: Starting Dashboards
2023-11-24 10:33:46.733064 INFO HASS: Connected to Home Assistant 2023.11.3
2023-11-24 10:33:46.736729 INFO AppDaemon: Starting Apps with 0 workers and 0 pins
2023-11-24 10:33:46.737218 INFO AppDaemon: Running on port 5050
2023-11-24 10:33:46.778903 INFO HASS: Evaluating startup conditions
2023-11-24 10:33:46.784431 INFO HASS: Startup condition met: hass state=RUNNING
2023-11-24 10:33:46.784746 INFO HASS: All startup conditions met
2023-11-24 10:33:46.817995 INFO AppDaemon: Got initial state from namespace default
2023-11-24 10:33:48.746734 INFO AppDaemon: Scheduler running in realtime
2023-11-24 10:33:48.748924 INFO AppDaemon: Adding /homeassistant/appdaemon/apps to module import path
2023-11-24 10:33:48.749305 INFO AppDaemon: Adding /homeassistant/appdaemon/apps/elco-remocon-net-appdaemon to module import path
2023-11-24 10:33:48.749649 INFO AppDaemon: Adding /homeassistant/appdaemon/apps/elco-remocon-net-appdaemon/assets to module import path
2023-11-24 10:33:48.749968 INFO AppDaemon: Adding /homeassistant/appdaemon/apps/elco-remocon-net-appdaemon/apps to module import path
2023-11-24 10:33:48.750269 INFO AppDaemon: Adding /homeassistant/appdaemon/apps/elco-remocon-net-appdaemon/apps/elco-remocon-net-appdaemon to module import path
2023-11-24 10:33:48.751954 WARNING AppDaemon: No app description found for: /homeassistant/appdaemon/apps/elco-remocon-net-appdaemon/apps/elco-remocon-net-appdaemon/elco-remocon-net-appdaemon.py - ignoring
2023-11-24 10:33:48.752808 INFO AppDaemon: App initialization complete

Would appreciate any help or hint.

Kind regards,
Robert

**Comment by Robi1976** [comment]
Found the solution. The app_dir function is not working properly. I copied your elco-remocon-net-appdaemon.py file from the /config folder and inserted to the apps-folder in the /addon_configs folder. Now it works again.

For anyone wondering how to access the /addon_configs folder. Opens Studio Code Server. Press the 3 lines at the top left. Then select File/Open Folder. Then you can select the /addon_configs folder. Then do the same again to get back to the /config folder.

My appdaemon.yaml in the /addon_configs folder looks as follows. Only changed secrets from "secrets: /config/secrets.yaml" to "secrets: /homeassistant/secrets.yaml"

```
secrets: /homeassistant/secrets.yaml
appdaemon:
  latitude: 52.379189
  longitude: 4.899431
  elevation: 2
  time_zone: Europe/Amsterdam
  plugins:
    HASS:
      type: hass
      ha_url: http://homeassistant.local:8123
      token: !secret appdaemon_token
http:
  url: http://homeassistant.local:5050
admin:
api:
hadashboard:
```
